"""add clients table

Revision ID: bc66109ccaed
Revises: 3205be7de43a
Create Date: 2024-11-08 15:02:26.914077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc66109ccaed'
down_revision: Union[str, None] = '3205be7de43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('birth', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('addr_number', sa.String(), nullable=False),
    sa.Column('addr_comp', sa.String(), nullable=True),
    sa.Column('addr_city', sa.String(), nullable=False),
    sa.Column('addr_region', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('resp_name', sa.String(), nullable=False),
    sa.Column('resp_cpf', sa.String(), nullable=False),
    sa.Column('resp_rg', sa.String(), nullable=False),
    sa.Column('resp_email', sa.String(), nullable=False),
    sa.Column('resp_phone', sa.String(), nullable=False),
    sa.Column('resp_birth', sa.String(), nullable=True),
    sa.Column('resp_prof', sa.String(), nullable=True),
    sa.Column('resp_sex', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
